# Add configuration values here, as shown below.
public_key: "54d25d5b516f8497942e" # replace it with your public key
private_key: "163c530fc62bca78d6fb"

# AWS_ACCESS_KEY: "AKIAIY5Z22XXMF32AJAQ"
# AWS_SECRET_KEY: "lCD36V1PlC1XO2QBaqSGZh0LUaMjF23xjnrtH"
# AWS_BUCKET: "trip-memories"

# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
